name: Frontend CI/CD

on:
  push:
    branches: [main]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USER }}/kanban-frontend:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USER }}/kanban-frontend:latest


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via Proxmox → LXC
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROXMOX_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}

          script: |
            pct exec 140 -- bash -c "
              cd /opt/kanban/task7 &&
              docker compose pull &&
              docker compose up -d
            "
